# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x181819ff
rootcolor = 0x2c2e34ff
bordercolor = 0x707789ff
focuscolor = 0xfc5d7cff
maximizescreencolor = 0x9ed072ff
urgentcolor = 0xf39660ff
scratchpadcolor = 0xb39df3ff
globalcolor = 0xa70020ff
overlaycolor = 0x457619ff
